### ISSUE TITLE
decimal places, and exclusion of closed orifice.

### ISSUE THREAD

**Issue by henryfan909** [OOW/gsi13#1]
Matt,

- Needed update for accuracy: [curve] and [xsections] export at 3 decimal places. Could you please increase those to export at 6 decimal places as a default setting - with option to set it (under database, systemwide_settings)?

- Wish list: In current version, export input file (INP) include closed orifice. Closed orifice are entry in [XSection] where ( Shape = "RECT_CLOSED" AND [GEOM2] = 0 ), along with corresponding entry in [Conduit] section -- e.g. entry "OR1atC29_shed_LID05_Storage-C29_WQ" -- would like such closed orifice excluded from export.

Thank you so much,
Henry

**Comment by edwardlennonjr** [comment]
Separated issues into two new issues.
